# Generated by Django 3.2.8 on 2021-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.CharField(default='orphan', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
