# Generated by Django 4.0.4 on 2022-11-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211130_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.CharField(choices=[('Orphan', 'Orphan'), ('Non-Orphan', 'Non-Orphan'), ('Single orphan', 'Single orphan')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
    ]
