# Generated by Django 4.0.4 on 2023-12-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_curricular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='kcpe',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='kcse',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='leadership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='refugee_or_immigrant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.CharField(choices=[('Orphan', 'Orphan'), ('Non-Orphan', 'Non-Orphan'), ('Single-orphan', 'Single-orphan')], max_length=15),
        ),
    ]
