# Generated by Django 3.2.8 on 2021-11-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
